[GLOBAL]
pants_version = "2.2.0"
pantsd = false

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[python-setup]
interpreter_constraints = [">=3.8"]

[pytest]
pytest_plugins.add = ["ipdb"]

[repl]
shell = "ipython"
